- name: Check if golang exists
  ansible.builtin.stat:
    path: /usr/local/go/bin/go
  register: go_bin

- name: Download golang
  ansible.builtin.get_url:
    url: "https://go.dev/dl/go1.26.3.linux-amd64.tar.gz"
    dest: /tmp/golang.tgz
    mode: "600"
  when: not go_bin.stat.exists

- name: Extract golang
  ansible.builtin.unarchive:
    src: /tmp/golang.tgz
    dest: /usr/local
    remote_src: true
  when: not go_bin.stat.exists

# https://go.dev/doc/telemetry
- name: Disable telemetry
  ansible.builtin.command:
    cmd: "{{ item }}"
  loop:
    - /usr/local/go/bin/go telemetry off
  become: true
  become_user: "{{ vm_user }}"
