- name: Setup Zig and ZLS
  vars:
    zig_version: "0.16.0"
    zls_version: "0.16.0"
    zig_arch: "x86_64-linux"
    zig_dir: "/usr/local/zig-{{ zig_arch }}-{{ zig_version }}"
    zig_tar: "zig-{{ zig_arch }}-{{ zig_version }}.tar.xz"
    zig_url: "https://ziglang.org/download/{{ zig_version }}/{{ zig_tar }}"
    zls_tar: "zls-{{ zig_arch }}.tar.xz"
    zls_url: "https://github.com/zigtools/zls/releases/download/{{ zls_version }}/{{ zls_tar }}"
  block:
    - name: Check if zig exists
      ansible.builtin.stat:
        path: "{{ zig_dir }}/zig"
      register: zig_bin

    - name: Download zig archive
      ansible.builtin.get_url:
        url: "{{ zig_url }}"
        dest: "/tmp/{{ zig_tar }}"
        mode: "0644"
      when: not zig_bin.stat.exists

    - name: Extract zig archive
      ansible.builtin.unarchive:
        src: "/tmp/{{ zig_tar }}"
        dest: /usr/local
        remote_src: true
      when: not zig_bin.stat.exists

    - name: Remove zig archive
      ansible.builtin.file:
        path: "/tmp/{{ zig_tar }}"
        state: absent

    - name: Check if zls exists
      ansible.builtin.stat:
        path: "{{ zig_dir }}/zls"
      register: zls_bin

    - name: Download zls archive
      ansible.builtin.get_url:
        url: "{{ zls_url }}"
        dest: "/tmp/{{ zls_tar }}"
        mode: "0644"
      when: not zls_bin.stat.exists

    - name: Extract zls archive
      ansible.builtin.unarchive:
        src: "/tmp/{{ zls_tar }}"
        dest: "{{ zig_dir }}"
        remote_src: true
      when: not zls_bin.stat.exists

    - name: Remove zls archive
      ansible.builtin.file:
        path: "/tmp/{{ zls_tar }}"
        state: absent

    - name: Add zig to user dotrc
      ansible.builtin.lineinfile:
        path: "/home/{{ vm_user }}/.dotrc"
        line: "export PATH=$PATH:{{ zig_dir }}/"

    - name: Add zig to root bashrc
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "export PATH=$PATH:{{ zig_dir }}/"
