- name: Make user directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
    mode: "0750"
    recurse: true
  with_items:
    - /home/{{ vm_user }}/.local/bin

- name: Install scripts
  ansible.builtin.copy:
    src: files/bin/
    dest: /home/{{ vm_user }}/.local/bin/
    mode: "0755"
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
    force: true
