- name: Configure Sway
  ansible.builtin.include_tasks: sway.yml

- name: Configure ZSH
  ansible.builtin.include_tasks: zsh.yml

- name: Configure dotrc
  ansible.builtin.include_tasks: dotrc.yml

- name: Configure system
  ansible.builtin.include_tasks: system.yml

- name: Configure font (Iosevka)
  ansible.builtin.include_tasks: iosevka.yml

- name: Install custom scripts to ~/.local/bin/
  ansible.builtin.include_tasks: bin.yml
