- name: Copy background
  ansible.builtin.copy:
    src: files/background.jpg
    dest: /usr/share/backgrounds/background.jpg
    mode: "0644"
    force: true

- name: Enable autologon
  ansible.builtin.template:
    src: templates/gdm_custom.j2
    dest: /etc/gdm3/custom.conf
    mode: "0644"

- name: Update /etc/hosts
  ansible.builtin.template:
    src: templates/hosts.j2
    dest: /etc/hosts
    mode: "644"

- name: Set DNS to 1.1.1.1 and 8.8.8.8
  community.general.nmcli:
    conn_name: "{{ ansible_facts['default_ipv4']['interface'] }}"
    type: "ethernet"
    dns4:
      - 1.1.1.1
      - 8.8.8.8
    dns4_ignore_auto: true
    state: present

- name: Populate /etc/environment with Wayland environment variables
  ansible.builtin.blockinfile:
    path: /etc/environment
    block: |
      WLR_DRM_NO_MODIFIERS=1
      WLR_RENDERER=pixman
      WLR_DRM_DEVICES=/dev/dri/card0
      QT_WAYLAND_DISABLE_WINDOW_DECORATION=1
      XDG_CURRENT_DESKTOP=sway
      QT_QPA_PLATFORM=wayland
      CLUTTER_BACKEND=wayland
      SDL_VIDEODRIVER=wayland
      MOZ_ENABLE_WAYLAND=1
      EDITOR=vim
      LS_COLORS="di=1:fi=96:*.m=31:*.py=32:*.txt=36:*.out=35"
    marker: "# {mark} ANSIBLE MANAGED WAYLAND ENV VARS"
    create: yes
    owner: root
    group: root
    mode: '0644'
