- name: Copy .zshrc
  ansible.builtin.copy:
    src: files/.zshrc
    dest: "/home/{{ vm_user }}/.zshrc"
    mode: "640"
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
    force: true

- name: Copy paradox.zsh
  ansible.builtin.copy:
    src: files/.paradox.zsh
    dest: "/home/{{ vm_user }}/.paradox.zsh"
    mode: "775"
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
    force: true

- name: "Set default shell for {{ vm_user }}"
  ansible.builtin.user:
    name: "{{ vm_user }}"
    shell: /bin/zsh
