- name: Download NFS Wolf
  ansible.builtin.get_url:
    url: https://github.com/StrongWind1/NFSWolf/releases/download/v0.6.0/nfswolf-linux-x86_64-full
    dest: /usr/local/bin/nfswolf
    mode: "0755"
