- name: Check if sx exists
  ansible.builtin.stat:
    path: /usr/local/bin/sx
  register: sx_bin

- name: Download sx
  ansible.builtin.get_url:
    url: "https://github.com/v-byte-cpu/sx/releases/download/v0.6.0/sx_0.6.0_linux_amd64.tar.gz"
    dest: /tmp/sx.tgz
    mode: "0600"
  when: not sx_bin.stat.exists

- name: Extract sx
  ansible.builtin.unarchive:
    src: /tmp/sx.tgz
    dest: /usr/local/bin
    remote_src: true
  when: not sx_bin.stat.exists
